"""Document readers: load text from .txt, .md, .docx and .pdf for detection.

The output is plain prose, deliberately: both detectors assume natural
language. Markdown or any other markup would be measured as part of the text —
Binoculars would score its perplexity, and `features.dash_rate` counts " - ",
which is exactly a Markdown bullet — so structure is dropped rather than
converted.

Word documents contribute body paragraphs and table cell text. Headers,
footers, footnotes and field results are skipped: they are boilerplate the
author never wrote, and they dilute the detection signal.

Requires python-docx for .docx support and pypdf for .pdf.
"""

from __future__ import annotations

from pathlib import Path

SUPPORTED_EXTENSIONS = {".txt", ".md", ".docx", ".pdf"}

# Word paragraph styles that are navigation furniture, never prose.
_FURNITURE_STYLE_PREFIXES = ("toc", "table of figures", "table of authorities", "index")


def _is_furniture(style_name: str | None) -> bool:
    if not style_name:
        return False
    lowered = style_name.strip().lower()
    return any(lowered.startswith(p) for p in _FURNITURE_STYLE_PREFIXES)


def _paragraph_prose(para) -> str:
    """The paragraph's text with Word field results removed.

    Field results are generated by Word, not written by the author: table-of-
    contents entries, page cross-references, and placeholders like "No table of
    figures entries found." or "Error! Reference source not found.". They are
    identified by structure (w:fldChar / w:instrText / w:fldSimple) rather than
    by matching their text, because Word localises the wording — the same
    placeholder appears in Greek in a Greek installation.

    A field embedded mid-sentence is left alone; only text that lies inside a
    field result is dropped.
    """
    from docx.oxml.ns import qn

    parts: list[str] = []
    depth = 0
    in_result = False

    for child in para._p.iterchildren():
        tag = child.tag
        if tag == qn("w:fldSimple"):
            continue  # the whole element is a field
        if tag == qn("w:hyperlink"):
            # TOC entries are hyperlinks; their runs carry the entry text.
            if not in_result:
                for run in child.findall(qn("w:r")):
                    parts.append("".join(t.text or "" for t in run.findall(qn("w:t"))))
            continue
        if tag != qn("w:r"):
            continue

        marker = child.find(qn("w:fldChar"))
        if marker is not None:
            kind = marker.get(qn("w:fldCharType"))
            if kind == "begin":
                depth += 1
            elif kind == "separate":
                in_result = True
            elif kind == "end":
                depth = max(0, depth - 1)
                if depth == 0:
                    in_result = False
            continue
        if child.find(qn("w:instrText")) is not None:
            continue  # the field's instructions, never displayed
        if in_result:
            continue  # generated text, not authored

        parts.append("".join(t.text or "" for t in child.findall(qn("w:t"))))

    return "".join(parts)


def read_docx(path: str | Path, include_tables: bool = True) -> str:
    try:
        from docx import Document
    except ImportError as e:
        raise ImportError(
            "Reading .docx requires python-docx: pip install python-docx"
        ) from e

    doc = Document(str(path))
    parts: list[str] = []

    for para in doc.paragraphs:
        if _is_furniture(getattr(para.style, "name", None)):
            continue
        text = _paragraph_prose(para).strip()
        if text:
            parts.append(text)

    if include_tables:
        for table in doc.tables:
            for row in table.rows:
                cells = [c.text.strip() for c in row.cells if c.text.strip()]
                if cells:
                    parts.append(" | ".join(cells))

    return "\n".join(parts)


def read_pdf(path: str | Path) -> str:
    """Extract text from a PDF's pages.

    Only works on PDFs with a real text layer. Scanned/image-only PDFs yield
    little or nothing — they would need OCR, which this toolkit does not do.
    """
    try:
        from pypdf import PdfReader
    except ImportError as e:
        raise ImportError("Reading .pdf requires pypdf: pip install pypdf") from e

    reader = PdfReader(str(path))
    parts = [text.strip() for page in reader.pages if (text := page.extract_text() or "").strip()]
    if not parts:
        raise ValueError(
            f"No extractable text in '{Path(path).name}'. If it is a scanned "
            "document it needs OCR first."
        )
    return "\n".join(parts)


def load_text(path: str | Path) -> str:
    """Load text from a file, dispatching on extension.

    Raises ValueError for unsupported extensions (including legacy .doc —
    convert those to .docx first, e.g. with LibreOffice:
    soffice --headless --convert-to docx file.doc).
    """
    path = Path(path)
    ext = path.suffix.lower()
    if ext == ".docx":
        return normalise_text(read_docx(path))
    if ext == ".pdf":
        return normalise_text(read_pdf(path))
    if ext in (".txt", ".md"):
        return normalise_text(path.read_text(encoding="utf-8"))
    if ext == ".doc":
        raise ValueError(
            "Legacy .doc is not supported. Convert to .docx first: "
            "soffice --headless --convert-to docx file.doc"
        )
    raise ValueError(
        f"Unsupported file type '{ext}'. Supported: {sorted(SUPPORTED_EXTENSIONS)}"
    )


def load_directory(directory: str | Path) -> dict[str, str]:
    """Load all supported files in a directory. Returns {filename: text}."""
    directory = Path(directory)
    out: dict[str, str] = {}
    for p in sorted(directory.iterdir()):
        if p.suffix.lower() in SUPPORTED_EXTENSIONS and p.is_file():
            out[p.name] = load_text(p)
    return out


# --------------------------------------------------------------------------
# Markdown export
#
# Detection runs on the flat prose above; this is a separate artefact, so that
# what a document contributed can be read back and kept. Here the structure is
# worth preserving, which is exactly why it must not be what gets scored.
# --------------------------------------------------------------------------


def _heading_level(style_name: str | None) -> int | None:
    """Markdown heading level for a Word style, or None if it is body text."""
    if not style_name:
        return None
    lowered = style_name.strip().lower()
    if lowered == "title":
        return 1
    if lowered.startswith("heading"):
        tail = lowered.removeprefix("heading").strip()
        if tail.isdigit():
            return min(int(tail) + 1, 6)
    return None


def docx_to_markdown(path: str | Path) -> str:
    """Convert a Word document to Markdown, keeping headings, lists and tables."""
    try:
        from docx import Document
    except ImportError as e:
        raise ImportError(
            "Reading .docx requires python-docx: pip install python-docx"
        ) from e

    doc = Document(str(path))
    lines: list[str] = []

    for para in doc.paragraphs:
        style = getattr(para.style, "name", None)
        if _is_furniture(style):
            continue
        text = _paragraph_prose(para).strip()
        if not text:
            continue
        level = _heading_level(style)
        if level:
            lines.append(f"{'#' * level} {text}")
        elif (style or "").strip().lower().startswith("list"):
            lines.append(f"- {text}")
        else:
            lines.append(text)
        lines.append("")

    for table in doc.tables:
        rows = [[c.text.strip().replace("|", r"\|") for c in row.cells] for row in table.rows]
        rows = [r for r in rows if any(r)]
        if not rows:
            continue
        header, *body = rows
        lines.append("| " + " | ".join(header) + " |")
        lines.append("| " + " | ".join("---" for _ in header) + " |")
        for row in body:
            # Pad or trim so ragged tables still render.
            row = (row + [""] * len(header))[: len(header)]
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def pdf_to_markdown(path: str | Path) -> str:
    """Convert a PDF to Markdown, one section per page.

    A PDF carries no heading structure to recover, so this preserves only the
    page boundaries that the text layer does give us.
    """
    try:
        from pypdf import PdfReader
    except ImportError as e:
        raise ImportError("Reading .pdf requires pypdf: pip install pypdf") from e

    reader = PdfReader(str(path))
    lines: list[str] = []
    for number, page in enumerate(reader.pages, 1):
        text = (page.extract_text() or "").strip()
        if not text:
            continue
        lines.append(f"## Page {number}")
        lines.append("")
        lines.append(text)
        lines.append("")

    if not lines:
        raise ValueError(
            f"No extractable text in '{Path(path).name}'. If it is a scanned "
            "document it needs OCR first."
        )
    return "\n".join(lines).strip() + "\n"


def to_markdown(path: str | Path) -> str:
    """Markdown rendering of a document, dispatching on extension."""
    path = Path(path)
    ext = path.suffix.lower()
    if ext == ".docx":
        return docx_to_markdown(path)
    if ext == ".pdf":
        return pdf_to_markdown(path)
    if ext in (".txt", ".md"):
        return path.read_text(encoding="utf-8")
    raise ValueError(
        f"Unsupported file type '{ext}'. Supported: {sorted(SUPPORTED_EXTENSIONS)}"
    )


def save_markdown(path: str | Path, out_path: str | Path | None = None) -> Path:
    """Write a document's Markdown rendering beside it (or to ``out_path``).

    Returns the path written. Never overwrites the source: converting a .md
    file in place would be a destructive no-op.
    """
    path = Path(path)
    out = Path(out_path) if out_path else path.with_suffix(".md")
    if out.resolve() == path.resolve():
        raise ValueError(f"Refusing to overwrite the source document: {path}")
    out.write_text(to_markdown(path), encoding="utf-8")
    return out


# --------------------------------------------------------------------------
# Normalisation
#
# Whitespace is not cosmetic here: newlines and spaces are tokens, so they
# count towards perplexity. Measured on a five-paragraph document, joining the
# paragraphs with "\n" rather than " " moved the score by 3.8% — wider than the
# margin many documents sit from the threshold, and enough to flip a verdict on
# formatting alone.
#
# python-docx, pypdf and a paste into the window each produce different
# whitespace for identical wording. Normalising here means the same document
# scores the same however it arrives.
# --------------------------------------------------------------------------

import re as _re

# Unicode spaces that Word and PDF exporters emit freely, plus zero-width
# characters that carry no meaning but do become tokens.
_UNICODE_SPACES = "               　"
_ZERO_WIDTH = "​‌‍﻿"

_TRANSLATION = {ord(c): " " for c in _UNICODE_SPACES}
_TRANSLATION.update({ord(c): None for c in _ZERO_WIDTH})

_HORIZONTAL_RUN = _re.compile(r"[ \t]+")
_BLANK_LINES = _re.compile(r"\n{2,}")


def normalise_text(text: str) -> str:
    """Tidy whitespace while keeping paragraphs readable.

    Used for what the reader returns and the window displays: line endings,
    Unicode spaces and stray indentation go, paragraph breaks stay. Idempotent.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.translate(_TRANSLATION)
    text = _HORIZONTAL_RUN.sub(" ", text)
    text = "\n".join(line.strip() for line in text.split("\n"))
    text = _BLANK_LINES.sub("\n", text)
    return text.strip()


def canonical_text(text: str) -> str:
    """One flat form for scoring, identical whatever the document arrived as.

    Line breaks go too, not only tidied. They look like structure but are not:
    pypdf emits a newline at every *visual* line wrap, python-docx at every
    paragraph, and a paste carries whatever the clipboard held. Keeping them
    would let the same wording score differently depending on which extractor
    produced it — measured at 3.8%, wider than the margin many documents sit
    from the threshold.

    The window still shows the readable form; only the scored string is flat.
    """
    return _HORIZONTAL_RUN.sub(" ", normalise_text(text).replace("\n", " ")).strip()
